### ISSUE TITLE
cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by mithomizuno** [Stichoza/google-translate-php#204] opened 2024-03-11 15:14 UTC
[ERROR] cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://translate.google.com/translate_a/single?client=gtx&hl=en&dt=t&dt=bd&dt=at&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&sl=en&tl=id&q=Hello%2C+Everyone%21&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=457496.51302

**Comment by Stichoza** [comment] 2024-03-11 17:19
duplicate of #91

**Closed by Stichoza** 2024-03-11 17:19 UTC
