### ISSUE TITLE
Please assist me

### ISSUE THREAD

**Issue by andrew-dev-3236** [Stichoza/google-translate-php#205] opened 2024-04-04 20:28 UTC

**Comment by andrew-dev-3236** [comment] 2024-04-04 20:29
I can't translate ever using this package. Ever never.

**Comment by andrew-dev-3236** [comment] 2024-04-05 01:52
Also solve this problem please.
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://translate.google.com/translate_a/single?client=gtx&hl=en&dt=t&dt=bd&dt=at&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&sl=en&tl=ka&q=Hello+again&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=589066.970356

**Comment by Stichoza** [comment] 2024-04-09 20:32
Duplicate of #91

**Closed by Stichoza** 2024-04-09 20:32 UTC
