### ISSUE TITLE
403 on strings with unicode characters

### ISSUE THREAD

**Issue by tehmaestro** [Stichoza/google-translate-php#42] opened 2016-01-12 08:31 UTC
Hi, so I discovered that the translation throws a Forbidden error when using unicode characters (I think that's what they are called). Here's an example: 
`I feel sad 😢`

Translating these does not work. It seems that the `d` array in `TL` function contains too many items. So something inside this loop

```
        for ($d = array(), $e = 0, $f = 0; $f < mb_strlen($a, 'UTF-8'); $f++) {
            $g = $this->charCodeAt($a, $f);
            if ( 128 > $g ) {
                $d[$e++] = $g;
            } else {
                if ( 2048 > $g ) {
                    $d[$e++] = $g >> 6 | 192;
                } else {
                    if ( 55296 == ($g & 64512) && $f + 1 < mb_strlen($a, 'UTF-8') && 56320 == ($this->charCodeAt($a, $f + 1) & 64512) ) {
                        $g = 65536 + (($g & 1023) << 10) + ($this->charCodeAt($a, ++$f) & 1023);
                        $d[$e++] = $g >> 18 | 240;
                        $d[$e++] = $g >> 12 & 63 | 128;
                    } else {
                        $d[$e++] = $g >> 12 | 224;
                        $d[$e++] = $g >> 6 & 63 | 128;
                    }
                }
                $d[$e++] = $g & 63 | 128;
            }
        }
```

does not work correctly with Unicode characters. My believe is that the function `charCodeAt` is to blame. It does not return the same values as javascript's `charCodeAt` for certain characters.

 Maybe someone can help ..

**Comment by Stichoza** [comment] 2016-01-12 18:22
I'm not sure if I understand the problem correctly, but first that comes to my mind is that some emojis are actually a combination of two unicode chars. Additionally, skin colored emojis might contain even more. I mean:

<img width="234" alt="screen shot 2016-01-12 at 22 18 58" src="https://cloud.githubusercontent.com/assets/1139050/12272602/c906e192-b97a-11e5-9f2c-72cca132d007.png">

And after all, unicode characters (like Georgian letters) work perfectly as you can see in [tests](https://github.com/Stichoza/google-translate-php/blob/master/tests/TranslationTest.php#L14-L40).

**Comment by tehmaestro** [comment] 2016-01-12 19:02
Sorry, maybe I was not clear, but when testing this string `I feel sad 😢`, or this one 'This is a test 😍' , both containing an emoji, the request does not work, it returns a Forbidden error.

 So this is a warning to users that might get the 403 error, and they don't know why, it might be because of some characters they have in their strings, which are not handled correctly by the `charCodeAt` function.

**Comment by manzoorwanijk** [comment] 2016-05-09 12:55
Any solution to the problem? I am also facing it.

**Comment by FDiskas** [comment] 2016-07-02 20:08
The same problem. I currently trying to translate the ```The :attribute must be an image.``` with the same 403 forbidden error.

**Comment by frzsombor** [comment] 2016-10-11 09:41
As a temporary solution, it could be a great idea, to remove all emojis from a string, before translating it. Here is a PHP function, that should do the work:

```PHP
function remove_emoji($string) {

    // Match Emoticons
    $regex_emoticons = '/[\x{1F600}-\x{1F64F}]/u';
    $clear_string = preg_replace($regex_emoticons, '', $string);

    // Match Miscellaneous Symbols and Pictographs
    $regex_symbols = '/[\x{1F300}-\x{1F5FF}]/u';
    $clear_string = preg_replace($regex_symbols, '', $clear_string);

    // Match Transport And Map Symbols
    $regex_transport = '/[\x{1F680}-\x{1F6FF}]/u';
    $clear_string = preg_replace($regex_transport, '', $clear_string);

    // Match Miscellaneous Symbols
    $regex_misc = '/[\x{2600}-\x{26FF}]/u';
    $clear_string = preg_replace($regex_misc, '', $clear_string);

    // Match Dingbats
    $regex_dingbats = '/[\x{2700}-\x{27BF}]/u';
    $clear_string = preg_replace($regex_dingbats, '', $clear_string);

    return $clear_string;
}
```

More information: 
http://stackoverflow.com/q/12807176/2953830
https://en.wikipedia.org/wiki/Emoji

**Comment by frzsombor** [comment] 2016-11-28 21:08
I've worked on this for almost two days in my freetime, and I think I FIGURED IT OUT!

The problem is that UTF-16 characters are handled very differently in PHP and JS.
This causes two problems in the PHP implementation of the token generation: a bug in string length, and a bug in charCodeAt. Here is my SO question and my answer:

http://stackoverflow.com/questions/40841149/unicode-charcodeat-equivalent-in-php/40853121

But for make this public, I will need as many of you as possible, to test, benchmark and check my code. I will make a pull request soon to make testing easier.

**Comment by frzsombor** [comment] 2018-06-25 14:24
Sorry for disappearing from this issue, now finally I had some time again to dig into this problem.
And I have good news: I think I got the solution! 

The root of the problem was that JS works and counts with UTF-16 code units while in PHP we are mostly working with UTF-8. And as long as we _have to_ work and count just like JavaScript, we have to convert strings to UTF-16 and extract informations from those variable. _(For some reason it looks like we were good until we stayed in Unicode BMP, but not outside that region)_

More details in _my PR_.

**Comment by carlitosz** [comment] 2018-11-12 06:36
I encountered the same issue that has been talked about in this thread, where strings with emojis are causing a 403 error. Was this issue ever solved?

**Comment by frzsombor** [comment] 2018-11-12 09:16
@carlitosz Yes, I hopefully fixed this bug in my pull request referenced above. However the latest (v3.2.13) release is a bit out of date, and it does not include the latest few commits yet. So either you clone the current state of the "master" or install the package with composer, [targeting the master branch](https://getcomposer.org/doc/articles/aliases.md#why-aliases-).

Alternatively, wait for @Stichoza to close this issue, push a new release version and use that ;)

**Comment by Stichoza** [comment] 2018-11-13 18:52
Oh sorry friends, my bad. Will push a new tag now 👍

**Closed** 2018-11-30 15:52 UTC
Labels: bug, help wanted
