### ISSUE TITLE
version 4.0 no longer working

### ISSUE THREAD

**Issue by kam2yar** [Stichoza/google-translate-php#117] opened 2019-08-24 09:49 UTC
hi 
i get this error today from the lumen

Client error: `POST https://translate.google.com/translate_a/single?client=t&hl=en&dt=t&dt=bd&dt=at&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&sl=en&tl=fa&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=725373.860675` resulted in a `400 Bad Request` response: <!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=de (truncated...)

and it's no longer working

**Comment by yanglongji** [comment] 2019-08-27 04:08
same with me

**Comment by shahzad-ahmad** [comment] 2019-08-27 07:30
Anybody can provide quick help here?

**Comment by frzsombor** [comment] 2019-09-09 11:49
@MuscledGeek 
> [...]
> 'proxy' => [
> 'http' => 'tcp://0.0.0.0:8080',
> 'http' => 'tcp://0.0.0.0:3123'//..add more if you wish
> ],
> [...]

This is **WRONG**, this is NOT how you set up proxies.
Declaring an array like this is not even valid in PHP (you have a duplicate key for 'http').
Please follow the [example](https://github.com/Stichoza/google-translate-php#http-client-configuration) on the main page. 

Also, this issue is a duplicate of #112 and that bug has been fixed in #109 (v4.0.2).
Make sure you are using the latest version of this library.

**Closed** 2019-10-29 14:00 UTC
