### ISSUE TITLE
POST http://translate.google.com/translate_a/t resulted in a `503 Service Unavailable` response

### ISSUE THREAD

**Issue by joeforjoomla** [Stichoza/google-translate-php#62] opened 2016-08-30 23:08 UTC
**Library stopped working**. Checking the response of the request to http://translate.google.com/translate_a/t  it looks like a 503 Service Unavailable

Server error response [url] http://ipv4.google.com/sorry/IndexRedirect?continue=http%3A%2F%2Ftranslate.google.com%2Ftranslate_a%2Ft&q=CGMSBFcVvDgY76SYvgUiGQDxp4NLWjSyK9Kcfu_3QluMCB6pWX64XWE [status code] 503 [reason phrase] Service Unavailable

**Comment by skyismine** [comment] 2016-08-31 06:56
I have the same error.

**Comment by lxedison** [comment] 2016-08-31 07:11
yesterday, i did a press test , i forked 10000+ process to request server at the same time,  and today i found 503 Service Unavailable， wish it has no relationship. T_T

**Comment by joeforjoomla** [comment] 2016-08-31 07:55
I don't think indeed. Today 503 Service Unavailable but this test by @helen5106  is still working http://www.liuxiatool.com/t.php

The library by @Stichoza is broken although.. hope they can have a look soon....

**Comment by joeforjoomla** [comment] 2016-08-31 08:09
The library fails with the following exception:

> Fatal error: Uncaught exception 'ErrorException' with message 'Server error response [url] http://ipv4.google.com/sorry/IndexRedirect?continue=http%3A%2F%2Ftranslate.google.com%2Ftranslate_a%2Ft&q=CGMSBFcVvDgY06CavgUiGQDxp4NLrwjog7r3dK2p6xQdFbOXFyCu9lU [status code] 503 [reason phrase] Service Unavailable' in E:\vhosts\HTML5\stichoza\vendor\stichoza\google-translate-php\src\Stichoza\GoogleTranslate\TranslateClient.php:215 Stack trace: #0 E:\vhosts\HTML5\stichoza\vendor\stichoza\google-translate-php\src\Stichoza\GoogleTranslate\TranslateClient.php(247): Stichoza\GoogleTranslate\TranslateClient->getResponse('Hello World!') #1 E:\vhosts\HTML5\stichoza\vendor\stichoza\google-translate-php\src\Stichoza\GoogleTranslate\TranslateClient.php(143): Stichoza\GoogleTranslate\TranslateClient->instanceTranslate('Hello World!') #2 E:\vhosts\HTML5\stichoza\index.php(8): Stichoza\GoogleTranslate\TranslateClient->__call('translate', Array) #3 E:\vhosts\HTML5\stichoza\index.php(8): Stichoza\GoogleTranslate\TranslateClient->translate('Hello in E:\vhosts\HTML5\stichoza\vendor\stichoza\google-translate-php\src\Stichoza\GoogleTranslate\TranslateClient.php on line 215

**Comment by skyismine** [comment] 2016-08-31 08:32
http://www.liuxiatool.com/t.php use GET request, google-translate-php use POST request.

**Comment by joeforjoomla** [comment] 2016-08-31 08:36
I tried changing from

> $response = $this->httpClient->post( $this->urlBase, array (
					'body' => $queryArray,
					'headers' => array (
							'User-Agent' => $ua,
							'Referer' => 'https://translate.google.com' 
					) 
			) );.

to

> $response = $this->httpClient->get ( $this->urlBase, array (
					'body' => $queryArray,
					'headers' => array (
							'User-Agent' => $ua,
							'Referer' => 'https://translate.google.com' 
					) 
			) );

but still not working

**Comment by skyismine** [comment] 2016-08-31 08:39
I have no idea, waiting for @Stichoza

**Comment by lxedison** [comment] 2016-08-31 09:35
online waiting

**Comment by joeforjoomla** [comment] 2016-08-31 09:55
I tested a bit more... it seems something having to do with the Guzzle lib maybe... waiting for @Stichoza and @helen5106

**Comment by prappo** [comment] 2016-08-31 11:04
I got the same problem , I built a project on it now nothing working .

**Comment by Stichoza** [comment] 2016-08-31 11:04
Hey guys, sorry to see this package failing. Will have a look, any help appreciated

**Comment by Stichoza** [comment] 2016-08-31 11:14
Pushed a new tag `v3.2.9` which fixes all problems except array translation.

**Comment by prappo** [comment] 2016-08-31 11:31
Still not working . just returning 'en' . @Stichoza

**Comment by treblaf** [comment] 2016-08-31 11:54
It working if you change 'dt' parameter from 'null' to 't' in query. I don't know why.
`        //'dt'       => null,`
`        'dt'       => 't',`

**Comment by joeforjoomla** [comment] 2016-08-31 12:00
not working at my end... just returning 'en' with 'dt' => null 
áƒ’áƒáƒ›áƒáƒ áƒ¯áƒáƒ‘áƒ áƒ›áƒ¡áƒáƒ¤áƒšáƒ˜áƒ and with 'dt' => 't'

**Comment by treblaf** [comment] 2016-08-31 12:03
@joeforjoomla can you give me the source text?

**Comment by joeforjoomla** [comment] 2016-08-31 12:12
Sorry @treblaf  my mistake, i confirm you that it's working with  'dt' => 't'

**Comment by joeforjoomla** [comment] 2016-08-31 12:19
Basically 3 changes are required:

endpoint from http://translate.google.com/translate_a/t  to http://translate.google.com/translate_a/single

client from 'client' => 'webapp' to 'client' => 't'

param 'dt' => 't'

**Comment by Stichoza** [comment] 2016-08-31 12:36
@joeforjoomla I did two of those. Didn't changed the last one. Feel free to send a PR as it's your fix

**Comment by joeforjoomla** [comment] 2016-08-31 12:46
I can do this, i think you should firstly create a new branch tag.

**Comment by Stichoza** [comment] 2016-08-31 17:54
#63 is merged now and a new tag published. Can you guys confirm it's working?

**Comment by iginikolaev** [comment] 2016-08-31 18:39
Works, as for me. Thanks.

**Comment by joeforjoomla** [comment] 2016-08-31 19:35
I confirm, as of now it's working for me, no issues

**Comment by natostanco** [comment] 2016-08-31 20:00
#56 added some compatibility for arrays...but can't translate strings of multiple languages (which if I remember correctly was only possible with `auto` anyway?)

**Comment by danielriosantos** [comment] 2016-09-01 05:47
Hi, not working again... error 503 even after https://github.com/Stichoza/google-translate-php/pull/64 ... Google might have change something...

**Comment by joeforjoomla** [comment] 2016-09-01 09:15
It's still working for me without #64 fix and not using arrays

**Comment by robov** [comment] 2016-09-01 11:09
Working again... AMAZING !!!... THANKS !!!!

**Comment by trenccan777** [comment] 2016-09-01 11:53
Hi, i think it's still not working. Even without #64 fix.

**Comment by avg0043** [comment] 2016-09-01 12:20
Hi, 3.2.11 version gives me 503 error..

**Comment by natostanco** [comment] 2016-09-01 14:23
#64 is only for arrays which is just some string parsing...the request has no changes, it has been said before that when google changes it takes some time for all the servers to catch up, so you need to make sure you are accessing the right server. There is also a tokenless handpoint that you can try:
`https://translate.googleapis.com/translate_a/single?client=gtx&sl=it&tl=en&dt=t&q=casa`

**Comment by joeforjoomla** [comment] 2016-09-01 15:46
Thanks to share the tokenless handpoint https://translate.googleapis.com/translate_a/single?client=gtx&sl=it&tl=en&dt=t&q=casa

**Comment by trenccan777** [comment] 2016-09-02 05:51
It's strange. I got two sites with this google translator script. One is working perfect other not. Still 503 error. I tried also tokenless handpoint. How long is it take for all the google servers to catch up? Can be more than 24 hours?

**Comment by Doxramos** [comment] 2016-09-03 02:38
![2016-09-02](https://cloud.githubusercontent.com/assets/1887043/18222210/bee742e2-7144-11e6-805e-857bc09ec618.png)

Currently. Checked on all URLs posted above.

**Comment by trenccan777** [comment] 2016-09-03 14:21
Any solution to this problem? Thanks

**Comment by amprodes** [comment] 2016-09-04 23:10
it's not working because google block the request ip? if we use proxy will help? because i installed the library and did like 3 request and everything was ok until like the four request i got "503 Service Unavailable"

**Comment by joeforjoomla** [comment] 2016-09-04 23:38
It looks weird that you guys can't get it working. After the changes explained above i got it working fine again both on the live server and localhost

**Comment by amprodes** [comment] 2016-09-04 23:56
yeah after multiples request google ban my ip! ... it's a work around this?

**Comment by trenccan777** [comment] 2016-09-06 20:30
Same problem. If is more requests from my site I get ban.

**Comment by joeforjoomla** [comment] 2016-09-06 20:41
Is there a way to determine if the ban is coming when using array to translate or even for normal single text?

**Comment by anilix** [comment] 2016-09-06 20:50
I've got exactly the same problem as @trenccan777 and @amprodes. It looks like google ban my server IP after several requests and all I get is 503 error:

`Fatal error: Uncaught exception 'ErrorException' with message 'Server error: `POST http://translate.google.com/translate_a/single` resulted in a `503 Service Unavailable` response`

**Comment by fero-sk** [comment] 2016-09-06 21:00
Ban after several requests (single text). Then after some time unban. Help :)

**Comment by joeforjoomla** [comment] 2016-09-06 21:03
So it looks that the problem is still not solved! Google still bans the IP
@Stichoza  please participate with us to fix the library

**Comment by amprodes** [comment] 2016-09-06 21:49
Well the problem is if you try to translate line by line... what i did was take my array and conver to string separated by || ... like this;

 // this is my array with non translated lines of text
  $textosA = array($lines_to_translate); 

//this is my array turning to a string with each line separated by ||
  $transBlock = implode('||',$textosA); 

//then we send just one request to google.translate
  $translated = $tr->translate($transBlock); 

 //and then we turn into an array again with our line texts already translated! .... bitches!!!
  $traduccion = explode('||',$translated);

**Comment by treblaf** [comment] 2016-09-07 04:05
Looks like the problem is in our request. We send all parameters and text in POST query, but web version of Google Translate send parameters in URL and ONLY text in POST (q=TEXT). So I changed the request in TranslateClient.php:

```
$queryArray = array_merge($this->urlParams, [
	//'text' => $data,
	'sl'   => $this->sourceLanguage,
	'tl'   => $this->targetLanguage,
	'tk'   => $this->tokenProvider->generateToken($this->sourceLanguage, $this->targetLanguage, $tokenData),
]);

$queryUrl = preg_replace('/%5B(?:[0-9]|[1-9][0-9]+)%5D=/', '=', http_build_query($queryArray));

$queryBodyArray = [
	'q' => $data,
];

$queryBodyEncoded = preg_replace('/%5B(?:[0-9]|[1-9][0-9]+)%5D=/', '=', http_build_query($queryBodyArray));

try {
	$response = $this->httpClient->post($this->urlBase, [
		'query' => $queryUrl,
		'body' => $queryBodyEncoded
		] + $this->httpOptions);
} catch (GuzzleRequestException $e) {
	throw new ErrorException($e->getMessage());
}
```

It's works for me now. Can you all test it too? 
Sorry for my english and code style.

**Comment by trenccan777** [comment] 2016-09-07 06:40
After trying your code I immediately get error 500. Maybe i made mistake by updating the code because from your post is hard to identify the changes.

**Comment by fero-sk** [comment] 2016-09-07 06:44
@treblaf - it looks working, thanks... waiting for IP ban :)

**Comment by treblaf** [comment] 2016-09-07 06:51
@trenccan777 you should replace this:
```
$queryArray = array_merge($this->urlParams, [
	'text' => $data,
	'sl'   => $this->sourceLanguage,
	'tl'   => $this->targetLanguage,
	'tk'   => $this->tokenProvider->generateToken($this->sourceLanguage, $this->targetLanguage, $tokenData),
]);

$queryUrl = preg_replace('/%5B(?:[0-9]|[1-9][0-9]+)%5D=/', '=', http_build_query($queryArray));

try {
	$response = $this->httpClient->post($this->urlBase, ['body' => $queryUrl] + $this->httpOptions);
} catch (GuzzleRequestException $e) {
	throw new ErrorException($e->getMessage());
}
```

to this:

```
$queryArray = array_merge($this->urlParams, [
    //'text' => $data,
    'sl'   => $this->sourceLanguage,
    'tl'   => $this->targetLanguage,
    'tk'   => $this->tokenProvider->generateToken($this->sourceLanguage, $this->targetLanguage, $tokenData),
]);

$queryUrl = preg_replace('/%5B(?:[0-9]|[1-9][0-9]+)%5D=/', '=', http_build_query($queryArray));

$queryBodyArray = [
    'q' => $data,
];

$queryBodyEncoded = preg_replace('/%5B(?:[0-9]|[1-9][0-9]+)%5D=/', '=', http_build_query($queryBodyArray));

try {
    $response = $this->httpClient->post($this->urlBase, [
        'query' => $queryUrl,
        'body' => $queryBodyEncoded
        ] + $this->httpOptions);
} catch (GuzzleRequestException $e) {
    throw new ErrorException($e->getMessage());
}
```
@fero-sk It's working for two hours, but I'm waiting for ban too)

**Comment by trenccan777** [comment] 2016-09-07 07:29
It looks like its working. Yesterday I get ban after 5 minutes. So i will give you feedback. Thanks

**Comment by joeforjoomla** [comment] 2016-09-07 08:33
Thanks guys, please test  test test and if the problem is really fixed sending only the text in POST we have to open a PR for the library

**Comment by treblaf** [comment] 2016-09-07 09:37
I opened PR. Maybe @Stichoza or somebody can correct my code, because my code style is not very good.

**Comment by joeforjoomla** [comment] 2016-09-07 10:16
Ok, but most important thing is understanding if this fixes the ban issue. If so, @Stichoza  will be happy to update the library

**Comment by trenccan777** [comment] 2016-09-07 10:35
Guys, I can confirm that the script is working without any problem. I have tested it on multiple sites.

**Comment by joeforjoomla** [comment] 2016-09-07 12:08
That's a great news. Please open a PR for @Stichoza to refactor the code and include it in the library

**Comment by fero-sk** [comment] 2016-09-11 16:48
@treblaf it's working fine

**Comment by amprodes** [comment] 2016-09-11 17:09
I try and now it's working

**Comment by gskema** [comment] 2016-09-13 06:09
Upgrading to `3.2.11` fixed the `503` error for me. Note: we only send single string translation requests.

**Comment by frzsombor** [comment] 2016-09-19 11:11
After a few hours of usage, unfortunately I get the _503 Service Unavailable_ error again. However it might be something like an IP ban, because I send a request about every 2 seconds to the Google translate server.

**Comment by trenccan777** [comment] 2018-05-21 20:08
Hi guys, it looks like this problem is happening again after some time. I have few websites with google api and one of them is getting 503 error. It is the most visited one. After few days the error I tried to run this script again and it worked for a few minutes and then again 503. As I can see I'm not the only one who is having this issue. https://github.com/matheuss/google-translate-api/issues/67 .

**Comment by fero-sk** [comment] 2018-05-21 22:21
Yes. 5 days ago Google started to block IP addresses... :(

**Comment by fero-sk** [comment] 2018-05-24 13:09
@Stichoza + @treblaf - could you please help us? we're getting 503 error after short time... then after cca. 24 hours it work's again (several minutes)

**Comment by fero-sk** [comment] 2018-05-25 19:42
Problem is with GoogleTokenGenerator.php - there's something changed...

**Comment by frzsombor** [comment] 2018-05-25 21:31
@fero-sk: I don't think anything changed in the token generation. I've tried special characters, numbers, long text, short text, everything, and all the generated tokens are valid, and

this library **STILL WORKS** for me every time.

However, as I'm still using this library DAILY for almost 2 years, I noticed that Google became much stricter a few days ago, just when @trenccan777 wrote his comment. They must have lowered the "number of allowed requests / minute / IP" because I also started getting 503 errors when I used an IP address for too long. 

**The solution:** still the same as I wrote above: buy and use proxies (just like me), change them frequently, more frequently than we had to in the past. If you don't want to pay for them, and you are using this package on your own computer, try changing your IP by restarting the router, etc. Also, IP bans will be removed automatically after some time (sorry, don't know exactly), so you don't have to buy new proxies over and over again.

**Comment by fero-sk** [comment] 2018-05-25 21:40
I don't think it's all about IP blocking. In browser translate.google.com - works, but Stichoza/google-translate-php - doesn't. Maybe some query parameters. If I'll find, I'll let you know.

**Comment by trenccan777** [comment] 2018-05-26 04:55
@fero-sk is your website still running after using the cookie? If yes, could you please provide me a location where did you put it in the code. A few days ago, I tried to change the IP of the website and it worked only hour maybe and than 503 again.

**Comment by fero-sk** [comment] 2018-05-26 06:10
@trenccan777 yes... still running ;)
$guzzle_conf = array(
	"headers" => array(
		"Cookie" => 'NID=XXX', // XXX - your NID Cookie
	),
);
$translator = new Stichoza\GoogleTranslate\TranslateClient("en", "de", $guzzle_conf);

**Comment by trenccan777** [comment] 2018-05-26 06:31
Thanks, bur I dont know if Im understand. You need to change the cookie regularly to keep the translation working?

**Comment by fero-sk** [comment] 2018-05-26 06:34
Just if it fails (503).

Dňa so 26. 5. 2018, 8:31 trenccan777 <notifications@github.com> napísal(a):

**Comment by trenccan777** [comment] 2018-05-26 11:12
@fero-sk  and where I can find this part of code in this package. In which file? Because I don't know where to implement this cookie "hack". Thanks.

**Comment by fero-sk** [comment] 2018-05-26 11:51
@trenccan777 when you're creating a translator (in your code, not in this package):

$guzzle_conf = array("headers" => array("Cookie" => 'NID=XXX'));
$tr = new TranslateClient('en', 'ka', $guzzle_conf);

**Comment by trenccan777** [comment] 2018-05-27 18:14
@fero-sk Is your translation still working? I have tried your NID Hack and after an hour received ban. What numbers are representing the XXX in the NID. It can be any integer? Thanks

**Closed** 2018-06-08 22:09 UTC
Labels: bug, help wanted

**Comment by sonamnrt** [comment] 2018-10-08 07:28
Server error: `POST https://translate.google.com/translate_a/single?client=webapp&hl=en&dt=t&sl=en&tl=hi&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=412082.31436` resulted in a `503 Service Unavailable` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>


Please solve

**Comment by sonamnrt** [comment] 2018-10-08 07:28
I have an issue with my translator
Server error: `POST https://translate.google.com/translate_a/single?client=webapp&hl=en&dt=t&sl=en&tl=hi&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=412082.31436` resulted in a `503 Service Unavailable` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>

**Comment by joeforjoomla** [comment] 2018-10-08 07:36
@sonamnrt that's not a problem of the library, looks like a problem at your end, it's working for me

**Comment by sonamnrt** [comment] 2018-10-08 07:45
but its not working for me please help what i can i do

**Comment by sonamnrt** [comment] 2018-10-08 07:47
@sonamnrt that's not a problem of the library, looks like a problem at your end, it's working for me


Please help what can i do

**Comment by sonamnrt** [comment] 2018-10-08 07:51
Server error: `POST https://translate.google.com/translate_a/single?client=t&hl=en&dt=t&sl=en&tl=hi&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=412082.31436` resulted in a `503 Service Unavailable` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><meta http-equiv="content-type" content="te (truncated...)
(View: C:\wamp64\www\newz-magazine\resources\views\template\slider.blade.php) (View: C:\wamp64\www\newz-magazine\resources\views\template\slider.blade.php)

**Comment by joeforjoomla** [comment] 2018-10-08 08:48
Read the dicussion, the answer has already been given:

> @Stichoza Also I think after fixing #96, it would be a good idea to share some informations about this on the main page, telling other developers that "503 Service Unavailable" is not definitely a problem with this package, but most likely it means their IP address is banned, and they should limit the requests or use proxies (correctly). And then, maybe this issue can be closed. :)

**Comment by sonamnrt** [comment] 2018-10-08 11:00
I think google block my ip please tell me what can i do for tranlator
 at morning Its work properly  but now its howing error

**Comment by fero-sk** [comment] 2018-10-08 11:02
Wait for 24 hours. Then it will be unblocked.

**Comment by frzsombor** [comment] 2018-10-08 12:03
@sonamnrt 
Please stop spamming this issue, you posted your error 3 times without any additional information! Your error is a [known limitation](https://github.com/Stichoza/google-translate-php/#known-limitations) and [using proxies](https://github.com/Stichoza/google-translate-php/#advanced-configuration) properly solves the problem. Please read the readme of the project before opening/posting to issues.

**Comment by rashidaghadiinfotech** [comment] 2018-11-22 11:11
Hello there, 

I am using this package since long, and it's a great work.

But nowadays I am facing the issue of 503 service unavailable. On my other server, it works very fine.
I have read comments and issues and tried to find out the solutions and it seems like our server IP has been banned in the google. I have read here comments and waited for more then 48 hours till now but I am not able to translate it. Do anyone in this have any solution regarding this ?  and how can I remove ban from google translate api ? or any other way to continue my site ?

https://islandus.is/wp-content/themes/bb-theme-child/rashid.php
vs 
http://aghadiinfotechforclient3.com/server07/translate/test.php

In these both, same code has been installed, but islandus does not work but client3 wors fine and providing the translations. 

Here is the coding, written for this translation word Welcome.

```
require 'vendor-translate/autoload.php';
use Stichoza\GoogleTranslate\TranslateClient;

try{
$string = "Welcome";
$tr = new TranslateClient();
$tr->setSource(null); 
$tr->setTarget('de'); 
echo $string."<br>";
$x = $tr->translate($string);
echo $x;
}
catch(ErrorException $e) {
	echo $e->getMessage();
}
```
Here is the server error I got.
`Server error: `POST https://translate.google.com/translate_a/single?client=t&hl=en&dt=t&sl=auto&tl=de&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=433950.44128` resulted in a `503 Service Unavailable` response:`

Please let me know what can be done regarding this.  
Thank you

**Comment by frzsombor** [comment] 2018-11-22 12:10
Unfortunately, the only one who knows how the ban system works and when a ban will be removed is Google. The 48 hours is just an estimate, but again, each case can be different, so no one knows the exact answers to questions like "when the ban will be removed?", "how to remove the ban?", etc. If you start getting IP bans from Google, the ONLY solutions is to **change your IP frequently**, for example using proxies.

Search for private/dedicated proxies, ask the seller/company if they are clean and safe to use with Google, and if yes, buy a few (let's say 5-10) and use them randomly on every request. Please don't even think about using shared or free proxies, they are over-abused and already blocked by Google.

**Comment by rashidaghadiinfotech** [comment] 2018-11-22 12:12
So any example, how can I use the proxy ? Do the hosting providers gives ip ? or anything else we can do with this ?

**Comment by frzsombor** [comment] 2018-11-22 12:18
The example is on the very first page of the project in the [Advanced configuration](https://github.com/Stichoza/google-translate-php#advanced-configuration) section and you can search google to find private/dedicated proxy providers. Please understand that I don't want to put links here, but there are a lot of companies and they are pretty easy to find.

**Comment by rashidaghadiinfotech** [comment] 2018-11-22 12:20
> The example is on the very first page of the project in the [Advanced configuration](https://github.com/Stichoza/google-translate-php#advanced-configuration) section and you can search google to find private/dedicated proxy providers. Please understand that I don't want to put links here, but there are a lot of companies and they are pretty easy to find.

So what I have to do is find IP address and add in advanced configuration. Right? Just adding proxy IP will resolve the issue?

**Comment by frzsombor** [comment] 2018-11-22 13:17
Using a proxy means that Google will see a different IP address (the proxy's IP) for your request, not your original one (that they may have blocked). If you set and use only one proxy with the same amount of requests, Google will block that proxy IP too. 
So the solution is to buy a few proxies and use them randomly. Without proxies, if you send 100 requests to Google from your server, they will see one IP address (your original server IP) with 100 requests and they will ban it. But if you buy 10 proxy and use one of them randomly on every request, then send 100 requests to Google, they will see 10 IP addresses with ~10 requests and _hopefully_ they will not ban any of them.

**Comment by mmejaz** [comment] 2020-06-02 08:53
> Basically 3 changes are required:
> 
> endpoint from http://translate.google.com/translate_a/t to http://translate.google.com/translate_a/single
> 
> client from 'client' => 'webapp' to 'client' => 't'
> 
> param 'dt' => 't'

please guide me where should I have to change 'dt'=>'t'. I
 don't have any idea where is the array
