### ISSUE TITLE
How can I translate my page web HTML into your library?

### ISSUE THREAD

**Issue by richardsonoge** [Stichoza/google-translate-php#206] opened 2024-05-11 14:46 UTC
Hi there!

I have my page web HTML [https://filesamples.com/samples/code/html/sample1.html](https://filesamples.com/samples/code/html/sample1.html) and would like to use your library to translate it. How can I do it? If you don't have it... Can you please add it for me?

**Comment by Stichoza** [comment] 2024-05-13 22:58
Hi! Check the pinned issue on the repo

duplicate of #23

**Closed by Stichoza** 2024-05-13 22:58 UTC

**Comment by richardsonoge** [comment] 2024-05-13 23:55
I've checked it and I still can't translate it correctly without losing the meaning of the HTML file. What should I do?
